name: Compose Rebuild Test Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'compose-rebuild-test/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy compose-rebuild-test
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          timeout: 60s
          command_timeout: 20m
          script: |
            echo "Connected to EC2"

            cd /home/ubuntu/devops-lab

            git pull origin main

            cd compose-rebuild-test

            docker compose down || true
            docker compose up --build -d

            docker ps
